server:
  port: 8088
spring:
  application:
    #应用的名称，可选
    name: buji_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/buji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  #邮箱配置
  mail:
    host: smtp.qq.com #发送邮件的服务器地址
    username: 1534293081@qq.com #登录qq邮箱的账号
    password: fpwkuzssezexjjba #开启IMAP/SMTP服务获得的授权码，而不是qq邮箱的登录密码
    default-encoding: utf-8
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
buji:
  path: D:\img\